import type { Metadata } from 'next'
import { Header } from '@/components/layout/header/Header'
import localFont from 'next/font/local'
import './globals.scss'

const bold = localFont({
    src: './fonts/Barlow-SemiBold.ttf',
    variable: '--bold',
})

const medium = localFont({
    src: './fonts/Barlow-Medium.ttf',
    variable: '--medium',
})

const regular = localFont({
    src: './fonts/Barlow-Regular.ttf',
    variable: '--regular',
})

const light = localFont({
    src: './fonts/Barlow-ExtraLight.ttf',
    variable: '--light',
})

export const metadata: Metadata = {
    title: 'Agathe Roger',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${bold.variable} ${medium.variable} ${regular.variable} ${light.variable}`}
            >
                <Header />
                {children}
            </body>
        </html>
    )
}
